### ISSUE TITLE
Protocol incompatibility

### ISSUE THREAD

**Issue by artemantonenko-exness** [dragonflyoss/client#1008]
### Bug report:

Trying to get peer to download image from seed peer and not from source. Configured enableBackToSource=false and disableBackToSource=true. Go dfdaemon works as expected. Rust client throws errors in log

<details>
<summary>Peer logs</summary>

```
  2025-02-28T14:21:34.906661608+00:00 ERROR  download with scheduler error: TonicStatus(Status { code: Internal, message: "failed to decode Protobuf message: Task.pieces: Peer.task: NormalTaskResponse.candidate_parents: AnnouncePeerResponse.response: invalid wire type: Varint (expected LengthDelimited)", source: None })
    at dragonfly-client/src/resource/task.rs:406
    in download
    in download_task with host_id: "192.168.97.9-c0680f04e25e", task_id: "75e9abfc5e0e9f7bcaca2c4f4475e4c0ec1b7cafb68b45928a78857f7dd84a48", peer_id: "192.168.97.9-c0680f04e25e-182d3e9f-419e-4a7e-9fb1-cb37f16fc622"

  2025-02-28T14:21:34.906690274+00:00 ERROR  download back-to-source is disabled, download with scheduler error: TonicStatus(Status { code: Internal, message: "failed to decode Protobuf message: Task.pieces: Peer.task: NormalTaskResponse.candidate_parents: AnnouncePeerResponse.response: invalid wire type: Varint (expected LengthDelimited)", source: None })
    at dragonfly-client/src/resource/task.rs:410
    in download
    in download_task with host_id: "192.168.97.9-c0680f04e25e", task_id: "75e9abfc5e0e9f7bcaca2c4f4475e4c0ec1b7cafb68b45928a78857f7dd84a48", peer_id: "192.168.97.9-c0680f04e25e-182d3e9f-419e-4a7e-9fb1-cb37f16fc622"

  2025-02-28T14:21:34.906714483+00:00 ERROR  download failed: unknown download failed
    at dragonfly-client/src/grpc/dfdaemon_download.rs:504
    in download_task with host_id: "192.168.97.9-c0680f04e25e", task_id: "75e9abfc5e0e9f7bcaca2c4f4475e4c0ec1b7cafb68b45928a78857f7dd84a48", peer_id: "192.168.97.9-c0680f04e25e-182d3e9f-419e-4a7e-9fb1-cb37f16fc622"

  2025-02-28T14:21:34.907524111+00:00 ERROR  download task failed: status: Internal, message: "unknown download failed", details: [], metadata: MetadataMap { headers: {} }
    at dragonfly-client/src/proxy/mod.rs:952
    in proxy_via_dfdaemon with host_id: "192.168.97.9-c0680f04e25e", task_id: "75e9abfc5e0e9f7bcaca2c4f4475e4c0ec1b7cafb68b45928a78857f7dd84a48", peer_id: "192.168.97.9-c0680f04e25e-182d3e9f-419e-4a7e-9fb1-cb37f16fc622"
    in http_handler
    in registry_mirror_http_handler
    in handler
```

</details>

### Expected behavior:

Expected peer to download pieces from seed peer. Instead it fails and image pull fails with `500 Internal Server Error`. 

### How to reproduce it:

<details>
<summary>Manager config</summary>

```yaml
console: true
auth:
  jwt:
    key: 'ZHJhZ29uZmx5Cg=='
database:
  type: postgres
  postgres:
    user: postgres
    password: 12345
    host: postgres
    port: 5432
    dbname: postgres
    migrate: true
  redis:
    addrs:
      - redis:6379
```

</details>

<details>
<summary>Scheduler config</summary>

```yaml
database:
  redis:
    addrs:
      - redis:6379
manager:
  addr: manager:65003
console: true
```

</details>

<details>
<summary>Rust seed peer config</summary>

```yaml
manager:
  addr: http://manager:65003
seedPeer:
  enable: true
  type: super
proxy:
  rules:
    - regex: '.*'
```

</details>

<details>
<summary>Rust non-seed peer config</summary>

```yaml
manager:
  addr: http://manager:65003
scheduler:
  enableBackToSource: false
seedPeer:
  enable: false
proxy:
  rules:
    - regex: '.*'
  disableBackToSource: true
```

</details>

<details>
<summary>Go seed peer config</summary>

```yaml
console: true
scheduler:
  manager:
    enable: true
    netAddrs:
      - type: tcp
        addr: manager:65003
    seedPeer:
      enable: true
      type: super
proxy:
  tcpListen:
    port: 65001
  registryMirror:
    dynamic: true
    url: https://private.registry
  proxies:
    - regx: '.*'
```

</details>

<details>
<summary>Go non-seed peer config</summary>

```yaml
console: true
scheduler:
  manager:
    enable: true
    netAddrs:
      - type: tcp
        addr: manager:65003
    seedPeer:
      enable: false
  disableAutoBackSource: true
proxy:
  tcpListen:
    port: 65001
  registryMirror:
    dynamic: true
    url: https://private.registry
  proxies:
    - regx: '.*'
```

</details>

Download an image through seed peer. Then try to download the same image but through non-seed peer.

### Environment:

- Client version: v0.2.16
- OS: macOS
- Kernel: orbstack
- Others: manager v2.2.0, scheduler v2.2.0
