### ISSUE TITLE
dfget 'Connect Dfdaemon Failed' if dfClient Pod rebuild

### ISSUE THREAD

**Issue by 40lsgy1** [dragonflyoss/client#1058]
### Bug report:

dfget在dfClient重建后执行报错

### Expected behavior:

dfget在dfClient重建成功后依然可以正常执行

### How to reproduce it:

正常情况：使用[HardLink](https://github.com/dragonflyoss/design/blob/main/systems-analysis/file-download-workflow-with-hard-link/README.md) 进行dfget的时候，可以执行成功

异常构造：手动删除dfClient的DamonSet的Pod，模拟dfClient异常重建的场景，业务Pod不重建，则此时尝试dfget，会报错，错误信息如下：
```
root@tool-c49b97c68-5lmvj:/var/lib/dragonfly# time dfget https://xxx.oss-cn-heyuan.aliyuncs.com/ideaIU-2024.3.5.dmg -O /var/lib/dragonfly/ideaIU-2024.3.5.dmg
Connect Dfdaemon Failed!
****************************************
Message:, can not connect ConnectError cause: transport error, please check the unix socket /var/run/dragonfly/dfdaemon.sock
****************************************

real	0m0.013s
user	0m0.004s
sys	0m0.011s
root@tool-c49b97c68-5lmvj:/var/lib/dragonfly# ls /var/run/dragonfly/dfdaemon.sock
/var/run/dragonfly/dfdaemon.sock
```

业务容器如下：
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tool
  labels:
    app: tool
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tool
  template:
    metadata:
      labels:
        app: tool
    spec:
      containers:
        - name: nginx
          image: docker.io/ubuntu:latest
          command: [ "/bin/sh" ]
          args: [ "-c", "while true; do sleep 3600; done" ]
          volumeMounts:
            - mountPath: /var/lib/dragonfly
              name: dfdaemon-storage
            - mountPath: /var/run/dragonfly/dfdaemon.sock
              name: dfdaemon-socket
      volumes:
        - name: dfdaemon-storage
          hostPath:
            type: Directory
            path: /var/lib/dragonfly
        - name: dfdaemon-socket
          hostPath:
            type: Socket
            path: /var/run/dragonfly/dfdaemon.sock
```

### Environment:
- Chart Version: dragonfly-1.3.15
- Client version: dfget 0.2.19 (beff3f87b, 2025-03-13)

**Comment by gaius-qi** [comment]
@40lsgy1 Please mount the socket's dir.

```yaml
          volumeMounts:
            - mountPath: /var/run/dragonfly
              name: dfdaemon-socket-dir
        - name: dfdaemon-socket-dir
          hostPath:
            type: Directory
            path: /var/run/dragonfly
```
