### ISSUE TITLE
use same config on v0.2.25 and v0.2.22 but v0.2.25 panic

### ISSUE THREAD

**Issue by slimhappy** [dragonflyoss/client#1118]
### Bug report:

I use the same config file to load dfdaemon，but v0.2.25 panic

### Expected behavior:

![Image](https://github.com/user-attachments/assets/f27ab7c2-74cd-4af2-85c1-cd5e782b3df5)

### Environment:
centos 7
arm64

**Comment by yxxhero** [comment]
@slimhappy need more info.

**Comment by slimhappy** [comment]
my config.yaml like this
```yaml
# verbose prints log to stdout.
verbose: true

log:
  level: info
host:
  idc: 'idc'
  location: 'shenzhen'
  ip: xx.xx.xx.xx # hidden my ip

server:
  pluginDir: /var/lib/dragonfly/plugins/dfdaemon/
  cacheDir: /var/cache/dragonfly/dfdaemon/

download:
  server:
    socketPath: /var/run/dragonfly/dfdaemon.sock
  rateLimit: 10GiB
  pieceTimeout: 30s
  concurrentPieceCount: 10

upload:
  server:
    port: 4000
  disableShared: false
  rateLimit: 10GiB

manager:
  addr: http://xx.xx.xx.xx:65003 # hidden my ip


scheduler:
  announceInterval: 10s
  scheduleTimeout: 30s
  maxScheduleCount: 5
  enableBackToSource: true

dynconfig:
  refreshInterval: 1m

storage:
  dir: /var/lib/dragonfly/
  keep: true
  writeBufferSize: 131072
  readBufferSize: 131072

gc:
  interval: 900s
  policy:
    taskTTL: 21600s
    distHighThresholdPercent: 80
    distLowThresholdPercent: 60

proxy:
  server:
    port: 4001
  rules:
    - regex: 'blobs/sha256.*'
  registryMirror:
    addr: https://index.docker.io
  disableBackToSource: false
  prefetch: false
  readBufferSize: 32768

metrics:
  server:
    port: 4002
```
